ReceiptsVersion: 2
DPOSVersion: 2
ChainConfig: 
  ContractEnabled: true
ContractLogLevel: "debug"
LoomLogLevel: "debug"
AppStore:
  Version: 3
  SaveEVMStateToIAVL: false
CachingStore:
  CachingEnabled: true