[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg list-features"
  Condition = "contains"
  Expected = ['dposv3']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg add-feature auto-enabled:feature-1 --build 0 -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "excludes"
  Expected = ['Error']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg add-feature auto-enabled:feature-2 --build 0 -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "excludes"
  Expected = ['Error']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg add-feature auto-enabled:feature-3 --build 111 --no-auto-enable -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "excludes"
  Expected = ['Error']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg list-features"
  Condition = "contains"
  Expected = ['auto-enabled:feature-1','auto-enabled:feature-2','auto-enabled:feature-3']
  
[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg add-feature chaincfg:v1.2 --build 0 -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "excludes"
  Expected = ['Error']

[[TestCases]]
  Delay = 20000
  RunCmd = "{{ $.LoomPath }} chain-cfg get-feature auto-enabled:feature-1"
  Condition = "contains"
  Expected = ['ENABLED','100']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg get-feature auto-enabled:feature-2"
  Condition = "contains"
  Expected = ['ENABLED','100']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg get-feature auto-enabled:feature-3"
  Condition = "contains"
  Expected = ['auto-enabled:feature-3','PENDING','111']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg remove-feature auto-enabled:feature-3 -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg list-features"
  Condition = "excludes"
  Expected = ['Error']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg set-validator-info --build 110 -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "excludes"
  Expected = ['Error']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg set-validator-info --build 10 -k {{index $.NodePrivKeyPathList 1}}"
  Condition = "excludes"
  Expected = ['Error']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg set-validator-info --build 10 -k {{index $.NodePrivKeyPathList 2}}"
  Condition = "excludes"
  Expected = ['Error']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg set-validator-info --build 10 -k {{index $.NodePrivKeyPathList 3}}"
  Condition = "excludes"
  Expected = ['Error']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg list-validators-info"
  Condition = "contains"
  Expected = ['validators','buildNumber','10','110']


