[[TestCases]]
  Dir = ""
  All = true
  RunCmd = "{{ $.LoomPath }} coin balance {{index $.AccountAddressList 0}}"
  Condition = "contains"
  Expected = [
    "Internal error: name is not registered"
  ]

[[TestCases]]
  Dir = ""
  RunCmd = "{{ $.LoomPath }} deploy-go -b new.json -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [
    "Attempting to deploy 2 contracts",
    "Contract coin deployed to address",
    "Contract dposV3 deployed to address",
    "2 contract(s) successfully deployed"
  ]
  # Default genesis.json file including coin and dposV3 contracts.
  Datafiles = [
    { Filename = "new.json", Contents = "{\"contracts\":[{\"vm\":\"plugin\",\"format\":\"plugin\",\"name\":\"coin\",\"location\":\"coin:1.0.0\",\"init\":null},{\"vm\":\"plugin\",\"format\":\"plugin\",\"name\":\"dposV3\",\"location\":\"dposV3:3.0.0\",\"init\":{\"params\":{\"validatorCount\":\"21\",\"electionCycleLength\":\"604800\"},\"validators\":[{\"pubKey\":\"3ZUdeKaVH+mcYMOjp85EAOiGLhgfo5Wd8HWv/sr6FWI=\",\"power\":\"10\"}]}}]}\" }" }
  ]

[[TestCases]]
All = true
RunCmd = "{{ $.LoomPath }} contract {{index $.ContractAddressList 0}}"
Condition = "contains"
Expected = ["Name","Address","Owner"]


[[TestCases]]
  Dir = ""
  All = true
  RunCmd = "{{ $.LoomPath }} coin balance {{index $.AccountAddressList 0}}"
  Condition = "contains"
  Expected = [
     "\"balance\": {",
      "\"Value\": 0",
     "}"
  ]

[[TestCases]]
  Dir = ""
  All = true
  RunCmd = "{{ $.LoomPath }} deploy-go -b new.json -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [
    "Attempting to deploy 2 contracts",
    "Contract coin already registered. Skipping",
    "Contract dposV3 already registered. Skipping",
    "0 contract(s) successfully deployed"
  ]
  # Default genesis.json file including coin and dposV3 contracts.
  Datafiles = [
    { Filename = "new.json", Contents = "{\"contracts\":[{\"vm\":\"plugin\",\"format\":\"plugin\",\"name\":\"coin\",\"location\":\"coin:1.0.0\",\"init\":null},{\"vm\":\"plugin\",\"format\":\"plugin\",\"name\":\"dposV3\",\"location\":\"dposV3:3.0.0\",\"init\":{\"params\":{\"validatorCount\":\"21\",\"electionCycleLength\":\"604800\"},\"validators\":[{\"pubKey\":\"3ZUdeKaVH+mcYMOjp85EAOiGLhgfo5Wd8HWv/sr6FWI=\",\"power\":\"10\"}]}}]}\" }" }
  ]
