[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 0}}"
  Condition = "contains"
  Expected = ["100000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 1}}"
  Condition = "contains"
  Expected = ["100000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = ["100000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call transfer {{index $.AccountAddressList 1}} 20 -p {{index $.AccountPrivKeyPathList 2}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 1}}"
  Condition = "contains"
  Expected = ["120000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = ["800000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Condition = "contains"
  Expected = ["{{index $.NodePubKeyList 0}}"]

[[TestCases]]
  RunCmd = "example-cli call transfer dposV2 90 -p {{index $.AccountPrivKeyPathList 0}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 0}}"
  Condition = "contains"
  Expected = ["10000000000000000000"]

# TODO Will bring back once rewards are finalized
# [[TestCases]]
#   RunCmd = "example-cli call balance dposV2"
#   Condition = "contains"
#   Expected = ["90000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call register_candidateV2 {{index $.AccountPubKeyList 0}} -p {{index $.AccountPrivKeyPathList 0}}"

[[TestCases]]
  RunCmd = "example-cli call register_candidateV2 {{index $.AccountPubKeyList 1}} -p {{index $.AccountPrivKeyPathList 1}}"

[[TestCases]]
  RunCmd = "example-cli call register_candidateV2 {{index $.AccountPubKeyList 2}} -p {{index $.AccountPrivKeyPathList 2}}"

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 1 -p {{index $.AccountPrivKeyPathList 0}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 2 -p {{index $.AccountPrivKeyPathList 1}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 3 -p {{index $.AccountPrivKeyPathList 2}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Condition = "contains"
  Expected = ["{{index $.NodePubKeyList 0}}"]

[[TestCases]]
  RunCmd = "example-cli call delegateV2 {{index $.AccountAddressList 0}} 1 -p {{index $.AccountPrivKeyPathList 0}}"

[[TestCases]]
  RunCmd = "example-cli call delegateV2 {{index $.AccountAddressList 1}} 2 -p {{index $.AccountPrivKeyPathList 1}}"

[[TestCases]]
  RunCmd = "example-cli call delegateV2 {{index $.AccountAddressList 2}} 3 -p {{index $.AccountPrivKeyPathList 2}}"

# [[TestCases]]
#   RunCmd = "example-cli call elect_delegationV2 -p {{index $.AccountPrivKeyPathList 0}}"

# reintroduce this after block rewards work
## the last round validators list would be paid for services
#[[TestCases]]
#  RunCmd = "example-cli call balance {{index $.NodeAddressList 0}}"
#  Condition = "contains"
#  Expected = ["10000000000000000000"]
#
## DPOS remaining after paying for 1 nodes
#[[TestCases]]
#  RunCmd = "example-cli call balance dposV2"
#  Condition = "contains"
#  Expected = ["80000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Condition = "contains"
  Expected = ["{{index $.AccountPubKeyList 0}}", "{{index $.AccountPubKeyList 1}}", "{{index $.AccountPubKeyList 2}}"]

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 0}}"
  Condition = "contains"
  Expected = ["9000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 1}}"
  Condition = "contains"
  Expected = ["11800000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.AccountAddressList 2}}"
  Condition = "contains"
  Expected = ["7700000000000000000"]

# [[TestCases]]
#   RunCmd = "example-cli call elect_delegationV2 -p {{index $.AccountPrivKeyPathList 0}}"

#[[TestCases]]
#  RunCmd = "example-cli call balance {{index $.AccountAddressList 0}}"
#  Condition = "contains"
#  Expected = ["20000000000000000000"]
#
#[[TestCases]]
#  RunCmd = "example-cli call balance {{index $.AccountAddressList 1}}"
#  Condition = "contains"
#  Expected = ["13000000000000000000"]
#
#[[TestCases]]
#  RunCmd = "example-cli call balance {{index $.AccountAddressList 2}}"
#  Condition = "contains"
#  Expected = ["9000000000000000000"]
#
#[[TestCases]]
#  RunCmd = "example-cli call balance dposV2"
#  Condition = "contains"
#  Expected = ["0"]
