[[TestCases]]
  RunCmd = "example-cli call balance {{index $.NodeAddressList 0}}"
  Condition = "contains"
  Expected = ["100000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.NodeAddressList 1}}"
  Condition = "contains"
  Expected = ["100000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Condition = "contains"
  Expected = ["{{index $.NodePubKeyList 0}}", "{{index $.NodePubKeyList 1}}"]

[[TestCases]]
  RunCmd = "example-cli call transfer dposV2 90 -p {{index $.NodePrivKeyPathList 0}}"

[[TestCases]]
  RunCmd = "example-cli call balance {{index $.NodeAddressList 0}}"
  All = true
  Condition = "contains"
  Expected = ["10000000000000000000"]

[[TestCases]]
  RunCmd = "example-cli call register_candidateV2 {{index $.NodePubKeyList 0}} 100 -p {{index $.NodePrivKeyPathList 0}}"

[[TestCases]]
  RunCmd = "example-cli call register_candidateV2 {{index $.NodePubKeyList 1}} 100 -p {{index $.NodePrivKeyPathList 1}}"

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 21 -p {{index $.NodePrivKeyPathList 0}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call approve dposV2 21 -p {{index $.NodePrivKeyPathList 1}}"
  Condition = ""

[[TestCases]]
  RunCmd = "example-cli call delegateV2 {{index $.NodeAddressList 0}} 10 -p {{index $.NodePrivKeyPathList 0}}"

# should fail since all delegations are locked for at least for the length of an
# election period
[[TestCases]]
  RunCmd = "example-cli call unbondV2 {{index $.NodeAddressList 0}} 10 -p {{index $.NodePrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ["Error"]

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Condition = "contains"
  Expected = ["{{index $.NodePubKeyList 0}}"]

[[TestCases]]
  RunCmd = "example-cli call delegateV2 {{index $.NodeAddressList 0}} 11 -p {{index $.NodePrivKeyPathList 0}}"

[[TestCases]]
  RunCmd = "example-cli call delegateV2 {{index $.NodeAddressList 1}} 21 -p {{index $.NodePrivKeyPathList 1}}"

[[TestCases]]
  RunCmd = "example-cli call unbondV2 {{index $.NodeAddressList 1}} 10 -p {{index $.NodePrivKeyPathList 1}}"
  Condition = "contains"
  Expected = ["Error"]

[[TestCases]]
  RunCmd = "example-cli call list_validatorsV2"
  Condition = "contains"
  Expected = ["{{index $.NodePubKeyList 0}}", "{{index $.NodePubKeyList 1}}"]
  Delay = 15000

[[TestCases]]
  RunCmd = "example-cli call unbondV2 {{index $.NodeAddressList 1}} 10 -p {{index $.NodePrivKeyPathList 1}}"

[[TestCases]]
  RunCmd = "example-cli call delegation_override {{index $.NodeAddressList 1}} {{index $.NodeAddressList 1}} 7600000 0 -p {{index $.NodePrivKeyPathList 1}}"

[[TestCases]]
  RunCmd = "example-cli call check_delegationV2 {{index $.NodeAddressList 1}} {{index $.NodeAddressList 1}}"
  Condition = "contains"
  Expected = ["7600000"]
