[[TestCases]]
  RunCmd = "{{ $.LoomPath }} deploy -b TestEvent.bin -n TestEvent -k {{index $.AccountPrivKeyPathList 0}}"
  Datafiles = [
    { Filename = "TestEvent.bin", Contents = "6080604052348015600f57600080fd5b5060ca8061001e6000396000f300608060405260043610603f576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063d0a2d2cb146044575b600080fd5b348015604f57600080fd5b50606c60048036038101908080359060200190929190505050606e565b005b807f6c2b4666ba8da5a95717621d879a77de725f3d816709b9cbe9f059b8f875e28460405160405180910390a2505600a165627a7a72305820f45ab9cd5176eb140cc2537286a1854a9538c364e3bee853c3278259ee5cf92c0029" }
  ]
  Condition = "contains"
  Expected = [ "New contract deployed" ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} callevm -i input1.bin -n TestEvent -k {{index $.AccountPrivKeyPathList 1}}"
  Datafiles = [
    { Filename = "input1.bin", Contents = "0xd0a2d2cb0000000000000000000000000000000000000000000000000000000000000001" }
  ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} callevm -i input2.bin -n TestEvent -k {{index $.AccountPrivKeyPathList 1}}"
  Datafiles = [
    { Filename = "input2.bin", Contents = "0xd0a2d2cb0000000000000000000000000000000000000000000000000000000000000002" }
  ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} callevm -i input3.bin -n TestEvent -k {{index $.AccountPrivKeyPathList 1}}"
  Datafiles = [
    { Filename = "input3.bin", Contents = "0xd0a2d2cb0000000000000000000000000000000000000000000000000000000000000003" }
  ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} callevm -i input4.bin -n TestEvent -k {{index $.AccountPrivKeyPathList 1}}"
  Datafiles = [
    { Filename = "input4.bin", Contents = "0xd0a2d2cb0000000000000000000000000000000000000000000000000000000000000003" }
  ]

# No filter return all four events.
[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getLogs","params":[{}],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [
                '"topics": [',
                '"0x6c2b4666ba8da5a95717621d879a77de725f3d816709b9cbe9f059b8f875e284"',
                '"0x0000000000000000000000000000000000000000000000000000000000000001"',
                '"0x0000000000000000000000000000000000000000000000000000000000000002"',
                '"0x0000000000000000000000000000000000000000000000000000000000000003"',
            ]

# filter against one topic
[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getLogs","params":[{"topics":[null,["0x0000000000000000000000000000000000000000000000000000000000000001"]]}],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [
              '"0x0000000000000000000000000000000000000000000000000000000000000001"',
             ]
[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getLogs","params":[{"topics":[null,["0x0000000000000000000000000000000000000000000000000000000000000001"]]}],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "excludes"
  Excluded = [
               '"0x0000000000000000000000000000000000000000000000000000000000000002"',
               '"0x0000000000000000000000000000000000000000000000000000000000000003"',
             ]

# filter topices are anded across different topics, "nonsese" and "0x0..."
[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getLogs","params":[{"topics":["nonsese",["0x0000000000000000000000000000000000000000000000000000000000000001"]]}],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "excludes"
  Excluded = [
              '"0x0000000000000000000000000000000000000000000000000000000000000001"',
             ]

# filter topices are ored in the same topic, "nonsese" or "0x0..."
[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getLogs","params":[{"topics":["0x6c2b4666ba8da5a95717621d879a77de725f3d816709b9cbe9f059b8f875e284",["0x0000000000000000000000000000000000000000000000000000000000000001","0x0000000000000000000000000000000000000000000000000000000000000002"]]}],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [
               '"0x0000000000000000000000000000000000000000000000000000000000000001"',
               '"0x0000000000000000000000000000000000000000000000000000000000000002"',
             ]
[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getLogs","params":[{"topics":["0x6c2b4666ba8da5a95717621d879a77de725f3d816709b9cbe9f059b8f875e284",["0x0000000000000000000000000000000000000000000000000000000000000001","0x0000000000000000000000000000000000000000000000000000000000000002"]]}],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "excludes"
  Excluded = [
               '"0x0000000000000000000000000000000000000000000000000000000000000003"',
             ]

[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["{{index $.AccountAddressList 1}}","latest"],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [ '"result": "0x4"' ]

 [[TestCases]]
   RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0x0a90050a8b0508011286050a00121f0a0764656661756c7412149a1ac42a17aad6dbc6d21c162989d0f7010740441ae004080112ce04608060405234801561001057600080fd5b5061022e806100206000396000f3fe608060405234801561001057600080fd5b506004361061005e576000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b1146100635780636d4ce63c14610091578063cf718921146100e2575b600080fd5b61008f6004803603602081101561007957600080fd5b8101908080359060200190929190505050610110565b005b610099610180565b604051808381526020018273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019250505060405180910390f35b61010e600480360360208110156100f857600080fd5b8101908080359060200190929190505050610192565b005b806000819055506000547f7e0b7a35f017ec94e71d7012fe8fa8011f1dab6090674f92de08f8092ab30dda33604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390a250565b60008060005433809050915091509091565b806000819055506000547fbd0b1e25f4b9c4b15621999967b6f720a9d31b208d1b70ec690fb4f46d445c8233604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390a25056fea165627a7a72305820eab32966bdd60595bc33cf239219f1b6804d6cd7287d7e9339dd539078103efc00291a0b53696d706c6553746f72651003124036ccdb9aa0cb1144fceb0a71679a7fbf4fa35531ab4485a69820e5534ae28ba32e4d2c13584cd3751807091c0f15e912c1c09e7b70adb387a67f1d468eaf89001a20f60c7e22684970ea51f6017c8b8add4fb614b515e816ae1b40afe4d2d03779e7"],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
   Condition = "excludes"
   Excluded = [ '"error":' ]
