[[TestCases]]
  RunCmd = "{{ $.LoomPath }} deploy -b SimpleStore.bin -n SimpleStore -k {{index $.AccountPrivKeyPathList 0}}"
  Datafiles = [
    { Filename = "SimpleStore.bin", Contents = "6060604052341561000f57600080fd5b60d38061001d6000396000f3006060604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c14606e575b600080fd5b3415605857600080fd5b606c60048080359060200190919050506094565b005b3415607857600080fd5b607e609e565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a723058202b229fba38c096f9c9c81ba2633fb4a7b418032de7862b60d1509a4054e2d6bb0029" }
  ]

[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getBlockTransactionCountByNumber","params":["earliest"],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [
              '"result": "0x0"',
              '"jsonrpc": "2.0"',
              '"id": 83'
             ]

[[TestCases]]
  RunCmd = "wait_for_block_height_to_reach 0 2"

[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getBlockTransactionCountByNumber","params":["0x2"],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [
              '"result": "0x1"',
              '"jsonrpc": "2.0"',
              '"id": 83'
             ]

[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getBlockTransactionCountByNumber","params":["pending"],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [
             'get number of transactions for pending blocks, not implemented yet'
             ]

[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getBlockTransactionCountByNumber","params":["0x10"],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [
                  '"jsonrpc": "2.0"',
                  '"id": 83',
                  '"error": {',
                  '"code": -32000',
                  '"message": "Server error"',
                  '"data": "loom error: requested block height 16 exceeds pending block height',
             ]

[[TestCases]]
    RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getTransactionByBlockNumberAndIndex","params":["0x2","0x0"],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
    Condition = "contains"
    Expected = [
            '"blockNumber": "0x2"',
            '"transactionIndex": "0x0',
            '"input": "0x6060604052341561000f57600080fd5b60d3806'
              ]

[[TestCases]]
  RunCmd = '/usr/bin/curl -X POST --data {"jsonrpc":"2.0","method":"eth_getTransactionByBlockNumberAndIndex","params":["0x2","0x1"],"id":83} {{index $.NodeProxyAppAddressList 0}}/eth'
  Condition = "contains"
  Expected = [
              '"error"',
              '"data": "loom error: tx index out of bounds'
             ]
