[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg list-features"
  Condition = "contains"
  Expected = ['registry:check-error']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} deploy -b SimpleStore.bin -n SimpleStore -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [
                "Runtime bytecode:",
                "[96 96 96 64 82 96 4 54 16 96 73 87 96 0 53 124 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 144 4 99 255 255 255 255 22 128 99 96 254 71 177 20 96 78 87 128 99 109 76 230 60 20 96 110 87 91 96 0 128 253 91 52 21 96 88 87 96 0 128 253 91 96 108 96 4 128 128 53 144 96 32 1 144 145 144 80 80 96 148 86 91 0 91 52 21 96 120 87 96 0 128 253 91 96 126 96 158 86 91 96 64 81 128 130 129 82 96 32 1 145 80 80 96 64 81 128 145 3 144 243 91 128 96 0 129 144 85 80 80 86 91 96 0 128 84 144 80 144 86 0 161 101 98 122 122 114 48 88 32 43 34 159 186 56 192 150 249 201 200 27 162 99 63 180 167 180 24 3 45 231 134 43 96 209 80 154 64 84 226 214 187 0 41]",
                "Transaction receipt:",
                "New contract deployed with address: "
             ]
  Datafiles = [
    { Filename = "SimpleStore.bin", Contents = "6060604052341561000f57600080fd5b60d38061001d6000396000f3006060604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c14606e575b600080fd5b3415605857600080fd5b606c60048080359060200190919050506094565b005b3415607857600080fd5b607e609e565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a723058202b229fba38c096f9c9c81ba2633fb4a7b418032de7862b60d1509a4054e2d6bb0029" }
  ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} deploy -b SimpleStore.bin -n SimpleStore -k {{index $.AccountPrivKeyPathList 1}}"
  Condition = "contains"
 Expected = ["name is already registered"]
  Datafiles = [
    { Filename = "SimpleStore.bin", Contents = "6060604052341561000f57600080fd5b60d38061001d6000396000f3006060604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c14606e575b600080fd5b3415605857600080fd5b606c60048080359060200190919050506094565b005b3415607857600080fd5b607e609e565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a723058202b229fba38c096f9c9c81ba2633fb4a7b418032de7862b60d1509a4054e2d6bb0029" }
  ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} callevm -i inputSet987.bin -n SimpleStore -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [
                "Call response:",
                "Transaction receipt:"
             ]
  Datafiles = [
    { Filename = "inputSet987.bin", Contents = "60fe47b100000000000000000000000000000000000000000000000000000000000003db" }
  ]


[[TestCases]]
  RunCmd = "{{ $.LoomPath }} static-call-evm -i inputGet.bin -n SimpleStore"
  Condition = "contains"
  Expected = [
               "Call response:"
             ]
  Datafiles = [
    { Filename = "inputGet.bin", Contents = "6d4ce63c" }
  ]

  [[TestCases]]
  Dir = ""
  RunCmd = "{{ $.LoomPath }} deploy-go -b new.json -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [
    "Attempting to deploy 1 contracts",
    "Attempting to deploy contract",
    "Contract SimpleStore already registered. Skipping",
    "0 contract(s) successfully deployed"
  ]
  # Default genesis.json file including coin and dposV3 contracts.
  Datafiles = [
    { Filename = "new.json", Contents = "{\"contracts\":[{\"vm\":\"plugin\",\"format\":\"plugin\",\"name\":\"SimpleStore\",\"location\":\"coin:1.0.0\",\"init\":null}]}"}
  ]

