[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg list-features"
  Condition = "contains"
  Expected = [ "auth:sigtx:tron", "auth:sigtx:eth" ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg feature-enabled auth:sigtx:eth"
  Condition = "contains"
  Expected = [ "true" ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg feature-enabled auth:sigtx:tron"
  Condition = "contains"
  Expected = [ "true" ]

# Should always be able to send ed25519 txs with the current chain ID, even when not explicitely
# configured in loom.yml and enabled via a feature flag.
[[TestCases]]
  RunCmd = "{{ $.LoomPath }} deploy -b SimpleStore.bin -k {{index $.AccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [ "New contract deployed with address: "  ]
  Datafiles = [
    { Filename = "SimpleStore.bin", Contents = "6060604052341561000f57600080fd5b60d38061001d6000396000f3006060604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c14606e575b600080fd5b3415605857600080fd5b606c60048080359060200190919050506094565b005b3415607857600080fd5b607e609e565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a723058202b229fba38c096f9c9c81ba2633fb4a7b418032de7862b60d1509a4054e2d6bb0029" }
  ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} deploy -b SimpleStore.bin -n SimpleStore --algo secp256k1 --caller-chain eth -k {{index $.EthAccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [ "New contract deployed with address: "  ]
  Datafiles = [
    { Filename = "SimpleStore.bin", Contents = "6060604052341561000f57600080fd5b60d38061001d6000396000f3006060604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c14606e575b600080fd5b3415605857600080fd5b606c60048080359060200190919050506094565b005b3415607857600080fd5b607e609e565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a723058202b229fba38c096f9c9c81ba2633fb4a7b418032de7862b60d1509a4054e2d6bb0029" }
  ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} callevm -i inputSet987.bin -n SimpleStore --algo secp256k1 --caller-chain eth -k {{index $.EthAccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [ "Call response: " ]
  Datafiles = [ { Filename = "inputSet987.bin", Contents = "60fe47b100000000000000000000000000000000000000000000000000000000000003db" } ]

# Tron
[[TestCases]]
  RunCmd = "{{ $.LoomPath }} static-call-evm -i inputGet.bin -n SimpleStore"
  Condition = "contains"
  Expected = [ "Call response: ", "[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 219]" ]
  Datafiles = [ { Filename = "inputGet.bin", Contents = "6d4ce63c" } ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} deploy -b SimpleStore.bin -n SimpleStore2 --algo tron --caller-chain tron -k {{index $.TronAccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [ "New contract deployed with address: "  ]
  Datafiles = [
    { Filename = "SimpleStore.bin", Contents = "6060604052341561000f57600080fd5b60d38061001d6000396000f3006060604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c14606e575b600080fd5b3415605857600080fd5b606c60048080359060200190919050506094565b005b3415607857600080fd5b607e609e565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a723058202b229fba38c096f9c9c81ba2633fb4a7b418032de7862b60d1509a4054e2d6bb0029" }
  ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} callevm -i inputSet987.bin -n SimpleStore2 --algo tron --caller-chain tron  -k {{index $.TronAccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [ "Call response: " ]
  Datafiles = [ { Filename = "inputSet987.bin", Contents = "60fe47b100000000000000000000000000000000000000000000000000000000000003db" } ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} static-call-evm -i inputGet.bin -n SimpleStore2"
  Condition = "contains"
  Expected = [ "Call response: ", "[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 219]" ]
  Datafiles = [ { Filename = "inputGet.bin", Contents = "6d4ce63c" } ]

# Binance
[[TestCases]]
  RunCmd = "{{ $.LoomPath }} deploy -b SimpleStore.bin -n SimpleStore2 --algo secp256k1 --caller-chain binance -k {{index $.BinanceAccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [ "New contract deployed with address: "  ]
  Datafiles = [
    { Filename = "SimpleStore.bin", Contents = "6060604052341561000f57600080fd5b60d38061001d6000396000f3006060604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c14606e575b600080fd5b3415605857600080fd5b606c60048080359060200190919050506094565b005b3415607857600080fd5b607e609e565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a723058202b229fba38c096f9c9c81ba2633fb4a7b418032de7862b60d1509a4054e2d6bb0029" }
  ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} callevm -i inputSet987.bin -n SimpleStore2 --algo secp256k1 --caller-chain binance  -k {{index $.BinanceAccountPrivKeyPathList 0}}"
  Condition = "contains"
  Expected = [ "Call response: " ]
  Datafiles = [ { Filename = "inputSet987.bin", Contents = "60fe47b100000000000000000000000000000000000000000000000000000000000003db" } ]

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} static-call-evm -i inputGet.bin -n SimpleStore2"
  Condition = "contains"
  Expected = [ "Call response: ", "[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 219]" ]
  Datafiles = [ { Filename = "inputGet.bin", Contents = "6d4ce63c" } ]