BFTLogLevel: "debug"
Peers: ""
ChainID: ""
RootDir: ""
DBName: ""
GenesisFile: ""
PluginsDir: ""
ContractLogLevel: ""
LoomLogLevel: ""
LogStateDB: false
LogEthDbBatch: false
UseCheckTx: true
RPCBindAddress: "tcp://0.0.0.0:46658"
# PlasmaCashEnabled: false
Oracle: "default:0xAfaA41C81A316111fB0A4644B7a276c26bEA2C9F"
SampleGoContract: true

TxLimiter:
  LimitDeploys: true
  LimitCalls: true
  CallSessionDuration: 3
  DeployerAddressList:
    - "default:0xBEC366d5566D112ee8B4ba61F1BE998a7fa099dE"
    - "default:0x40352F3aeD8E7281795dEf0CA7581F41DbE41F5B"
    - "default:0x2Ff9aB3aBDbC79efD22e3AC79787d8f9B5F99B40"
CallSessionDuration: 5

ContractLoaders:
  - "static"
  - "dynamic"
  - "external"

Karma:
  Enabled: true
  UpkeepEnabled: true
  MaxCallCount:  10
  SessionDuration: 60

BlockIndexStore:
  Enabled: true
  DBBackend: "goleveldb"
  DBName: "block_index"
  CacheSizeMegs: 128
  WriteBufferMegs: 64

ChainConfig:
  ContractEnabled: true

Auth:
  Chains:
    default:
      TxType: "loom"
    eth:
      TxType: "eth"
      AccountType: 1

HsmConfig:
  HsmEnabled: false
  HsmDevType: "yubihsm"
  HsmConnURL: "localhost:12345"
  HsmAuthKeyID: 1
  HsmAuthPassword: "password"
  HsmSignKeyDomain: 1

Metrics:
  BlockIndexStore: false
  EventHandling: true

GoContractDeployerWhitelist:
  Enabled: true
  DeployerAddressList:
    - "0xBEC366d5566D112ee8B4ba61F1BE998a7fa099dE"
    - "0x40352F3aeD8E7281795dEf0CA7581F41DbE41F5B"
    - "0x2Ff9aB3aBDbC79efD22e3AC79787d8f9B5F99B40"

DPOSv2OracleConfig:
  Enabled: false
  StatusServiceAddress: "0xBEC366d5566D112ee8B4ba61F1BE998a7fa099dE"
  MainnetPollInterval: 1
  #Reading in DAppChainCfg fails
  #DAppChainCfg:
  #  WriteURI: "tcp://0.0.0.0"
  #  ReadURI: "tcp://0.0.0.1"
  #  PrivateKeyPath: "tcp://0.0.0.2"

EventDispatcher:
  Dispatcher: log

EventStore:
  DBName: "event"
  DBBackend: "goleveldb"

